### ISSUE TITLE
Extra text after 'Attach file'

### ISSUE THREAD

**Issue by OolonColoophid** [chrisbra/CheckAttach#12]
Hi there

Great plugin---thanks.

When the plugin is triggered, I'm getting some pre-filled text in the input field (attached). Any ideas? Looks to me like some comment code in the plugin itself...

Cheers

Ian

<img width="1194" alt="footer" src="https://cloud.githubusercontent.com/assets/18744451/23140527/0fdceb52-f7aa-11e6-84ec-a1e0323b666c.png">

**Comment by chrisbra** [comment]
Not sure, looks like something isn't really cleaning up the commandline. Don't know, why this would happen. I think you need to bisect your plugins to find the problem.
