### ISSUE TITLE
External file browser option does not work in Neovim

### ISSUE THREAD

**Issue by has2k1** [chrisbra/CheckAttach#13]
I get the following

```
must run ranger from terminal
```

This is an upstream issue, see https://github.com/ranger/ranger/issues/279 and https://github.com/neovim/neovim/issues/1496.

Maybe a work around exists. This [fugitive patch](https://github.com/tpope/vim-fugitive/commit/4cc201cbe3a0c3faa4cde1b82ba941d410e5e81c) solved a similar [issue](https://github.com/tpope/vim-fugitive/issues/618). There is some discussion at the [PR](https://github.com/tpope/vim-fugitive/pull/624).

From what I am able to make of the pieces, the solution would be in the [ExternalFileBrowser](https://github.com/chrisbra/CheckAttach/blob/17e8e37e348a93f2a2104f07f1224c9c8798f85e/ftplugin/mail/CheckAttach.vim#L206) function and have the form

```vim
" Call external File Browser
if exists(':terminal')  " Neovim
    tabnew
    execute 'terminal ' s:external_file_browser a:pat
    " Deal with the consequences of opening ranger in a new tab and that
    " :terminal spawns a shell. <-- This is the hurdle
else  " Vim
    exe ':sil !' s:external_file_browser   a:pat
endif
```

**Comment by chrisbra** [comment]
PR welcome. As I do not use neovim, i cannot write code for this.
