### ISSUE TITLE
skip reminder after attaching file

### ISSUE THREAD

**Issue by Konfekt** [chrisbra/CheckAttach#16]
Every time the buffer is saved and a keyword is recognized --- and there are a bunch now, making it quite likely --- CheckAttach asks to attach a file.

How about skipping the reminder in case the user already attached a file, that is, there's a line 

Attach: ...

in the header?

**Comment by chrisbra** [comment]
That's what [that](https://github.com/chrisbra/CheckAttach/blob/master/doc/CheckAttach.txt#L107-L115) is for, isn't it?

**Comment by Konfekt** [comment]
Thank you! Sorry for never having noticed that option.
