### ISSUE TITLE
make autocmd after buffer write optional

### ISSUE THREAD

**Issue by Konfekt** [chrisbra/CheckAttach#17]
For example, here's a nested autocmd that saves the buffer after Vim losing focus. So, in the likely event that CheckAttach recognizes a keyword like 'atttach', it will ask for attaching a file every time when returning to Vim.

How about making that Check optional? Instead, thinking of a mutt user that uses Vim as its text editor, the autocmd reminding the user to add an attachment when quitting Vim seems the most useful and indispensable.

**Comment by chrisbra** [comment]
Yeah, it also often bothers me, that the check triggers on each BufWrite command. However, I am not sure, how to postpone it until just before quitting Vim and going back to mutt. And even if you could, one would not have the chance to check that the correct file has been attached. Perhaps, it would be better for your autocommand to do a `:noa :w`?

**Comment by Konfekt** [comment]
Well, another idea: If the user explicitely refused to attach a file, that is, escaped the attachment dialogue (hit enter or space), then further propositions could be disabled (say at least if `let g:checkattach_once = 'y'`).

**Comment by chrisbra** [comment]
will think about it.

**Comment by chrisbra** [comment]
Please check current head.

**Comment by Konfekt** [comment]
Thanks! Works.
