### ISSUE TITLE
Replace BufWriteCmd by BufWrite event

### ISSUE THREAD

**Issue by Konfekt** [chrisbra/CheckAttach#22]
By the way, CheckAttach uses `BufWriteCmd` which is not recommended; see :help Write-Cmd. 
For example, often the buffer cannot be written and has to be quit unmodified. Why not replace it by a `BufWrite` event?

**Comment by chrisbra** [comment]
I remember, when initially creating it, I had a problem that only worked with a custom BufWriteCmd, so that's why I used it for that and it worked fine until now.

**Comment by Konfekt** [comment]
It is `Cmd-event`. The problem is that sometimes the buffer cannot be written and has to be quit unmodified. Also, the BufWriteCmd says that the command should NOT change the buffer, that is 'The buffer contents should not be changed.'

**Comment by chrisbra** [comment]
If the buffer cannot be written (or the `BufWriteCmd`) fails, you can always use `:noa :w` or even better disable the plugin `:DisableCheckAttach` command.
