### ISSUE TITLE
Prevent search in signature of mail

### ISSUE THREAD

**Issue by jerri** [chrisbra/CheckAttach#25]
Unfortunately our companies signature mentions attachements, so this plugin is always triggered, which is somehow annoying. :-)
I checked out the code, but didn't yet see immediately how to change it. In principle the search should ignore any text below a line containing the string `-- ` (two minus signs followed by a space).
Would it be possible to add this kind of restriction?

**Comment by chrisbra** [comment]
good suggestion. Should be fixed already ;)

**Comment by jerri** [comment]
Great. Thanks!
