### ISSUE TITLE
One line message not matched

### ISSUE THREAD

**Issue by dbeniamine** [chrisbra/CheckAttach#7]
Hello,

First of all thanks for this plugin it is very usefull, I've juste downloaded it but I already love it !
Sadly I encounter an issue with one line message, for example if I write only
There is the promised attachement
Nothing is detected, it seems that I have to add a first line with some text and on empty line for the match to be done, something like the following will be recognised
Hello,

There is the promised attachement

I'am on the latest commit of the github repo:
commit 0e4e32cf6431f424a5d48fbc8c3431c7d684441b
Author: Christian Brabandt <cb@256bit.org>
Date:   Thu Jan 15 21:02:11 2015 +0100

    This is release 0.17

vim --version:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 30 2014 04:22:06)
Included patches: 1-488
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by jamessan@
Huge version with GTK2 GUI.

Bests,
David

**Comment by chrisbra** [comment]
Attaching using the pseudo Attach: header only works if you have :set edit_headers in your .muttrc set. If this is done, that you will always have an empty line above. So even if I did change it to support your single line mail, the attachment wouldn't be recognized by mutt and you would end up with a mail containing the Attachment line plus your single line.

**Comment by dbeniamine** [comment]
My Bad then the issue was between the chair and the keyboard ...
