### ISSUE TITLE
Append Attach: lines after lines starting with ^\w+:

### ISSUE THREAD

**Issue by Konfekt** [chrisbra/CheckAttach#9]
Currently they are appended before the first empty line. Instead, append them after the first line not of the format ^\w+:.

**Comment by chrisbra** [comment]
> Currently they are appended before the first empty line. Instead,
> append them after the first line not of the format ^\w+:. 

Is there a reason for this change?

**Comment by Konfekt** [comment]
Yes, currently, after attaching files the e-mail reads
```
From: Enno Nagel <enno.nagel@uni-muenster.de>
To: chrisbra@github.com
Cc: 
Bcc: 
Subject: issue
Reply-To: 
X-PGP-Key: https://www.magentacloud.de/api/sharelink/download?id=C6mYEgEp
OpenPGP: url=https://www.magentacloud.de/api/sharelink/download?id=C6mYEgEp;id=358CAF3AA77F49B0CE1DD30FDE06116C6C25A1A4
Hey Chris,
Attach: /tmp/epn27060/text_7

This is the issue.

Best

  Konfekt

```

**Comment by chrisbra** [comment]
Ah okay, I see the problem. I always thought, this was illegal for mut, but apparently this works just find. Will fix.

**Comment by Konfekt** [comment]
Thank you!
